In [24]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
arr[:,2]

array([ 3,  8, 13, 18, 23])

In [13]:
arr[3,1]

17

In [28]:
arr[3:5,3]

array([19, 24])

# BOOLEAN INDEXING

In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [31]:
data = np.random.randn(7, 4)
data

array([[ 1.45732541,  0.65077582,  0.46959231,  1.84333767],
       [ 0.61960708,  0.75482938, -0.79417635, -0.67982198],
       [ 0.04959372, -0.79187   , -0.24446862, -0.63307467],
       [ 1.49210064, -0.17533824,  1.66435345, -0.09968811],
       [-0.14475555,  0.19671044, -0.21552706,  0.61034655],
       [ 0.14172629,  1.2908008 ,  0.58322436,  0.96082017],
       [ 1.1029822 , -1.03142887,  1.12150871, -0.65211847]])

In [32]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [34]:
data[data>1]

array([1.45732541, 1.84333767, 1.49210064, 1.66435345, 1.2908008 ,
       1.1029822 , 1.12150871])

In [35]:
#if we need exact values we should put queries in dataframe or if we need overall so we just ask our queries

In [37]:
print(names == 'Bob')

[ True False False  True False False False]


In [38]:
data[names =='Bob']

array([[ 1.45732541,  0.65077582,  0.46959231,  1.84333767],
       [ 1.49210064, -0.17533824,  1.66435345, -0.09968811]])

In [39]:
data

array([[ 1.45732541,  0.65077582,  0.46959231,  1.84333767],
       [ 0.61960708,  0.75482938, -0.79417635, -0.67982198],
       [ 0.04959372, -0.79187   , -0.24446862, -0.63307467],
       [ 1.49210064, -0.17533824,  1.66435345, -0.09968811],
       [-0.14475555,  0.19671044, -0.21552706,  0.61034655],
       [ 0.14172629,  1.2908008 ,  0.58322436,  0.96082017],
       [ 1.1029822 , -1.03142887,  1.12150871, -0.65211847]])

In [50]:
data = np.random.randn(7, 4)
data

array([[-3.0097373 ,  0.28824566, -0.09997055,  1.37360869],
       [ 1.94922585,  1.68134575,  2.70714854,  0.57031196],
       [-1.45116137,  0.53604803, -0.50355223,  1.67314529],
       [-0.06450396,  0.17713139,  1.25638796,  1.7521168 ],
       [ 0.1516976 ,  0.91904901, -0.58396358, -0.10646817],
       [ 0.36903863, -0.20554928,  0.65769323,  1.61977096],
       [ 0.92055177,  0.72125022,  0.47084378,  2.13546111]])

In [52]:
bol = np.array([True,False,False,False,False,True,False],dtype = "bool")
               
data[bol]

array([[-3.0097373 ,  0.28824566, -0.09997055,  1.37360869],
       [ 0.36903863, -0.20554928,  0.65769323,  1.61977096]])

In [53]:
data[True,False,False,False,False,True,False]

array([], shape=(0, 7, 4), dtype=float64)

In [78]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [79]:
cond = names !='Bob'
cond

array([False,  True,  True, False,  True,  True,  True])

In [86]:
names[cond]

array(['Joe', 'Will', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [92]:
data = np.random.randn(7, 4)
data

array([[-1.37542241,  1.95633069, -0.37061981, -2.78663753],
       [-1.00108546,  0.82411674, -1.15275754, -0.67975977],
       [ 0.08995222,  0.74979736, -0.45484248,  2.17902106],
       [-1.03747946,  0.61475447, -1.27122091, -0.23738685],
       [ 1.39159022,  0.82471523,  0.63180149, -0.13624753],
       [-0.67320986,  0.89192832,  0.88969383,  0.11960226],
       [ 0.50666799, -0.34591235, -0.40026994, -0.83269667]])

In [95]:
data = np.arrange(28).reshape(7,4)
print(data)

AttributeError: module 'numpy' has no attribute 'arrange'

In [96]:
#we use amprsnt for and & use pipe for or

In [100]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [105]:
cond = (names =="Bob) | (names =="Joe")
cond

SyntaxError: invalid syntax (<ipython-input-105-972c423e6179>, line 1)

# Fancy Indexing

In [110]:
arr = np.empty((8, 4))

In [117]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [123]:
arr[[4,0,1,2],[2,3,0,1]]

array([4., 0., 1., 2.])

In [14]:
t = arr:7
t

NameError: name 'arr' is not defined

In [11]:
arr = np.arrange(32).reshape(8,4)
    print(arr)

#1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[[0,3,1,2]]

IndentationError: unexpected indent (<ipython-input-11-9da00eefe83c>, line 2)

In [9]:
arr[[1,5,7,2]][:,[0,3,1,2]]
arr

NameError: name 'arr' is not defined

In [12]:
array.transpose()

NameError: name 'array' is not defined

In [15]:
#sets finish the repetetive value as well as unique function also do the same job

# Concatenation

In [ ]:
arr = np.arange(6)

In [22]:
arr1 = arr.reshape((3, 2))

In [23]:
arr2 = np.random.randn(3, 2)

In [24]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.91075929, -0.14314335],
       [-0.37255076, -0.50784828],
       [-0.01510349, -0.09954732]])

# Stacking

In [29]:
np.stack([arr1,arr2])

array([[[ 0.        ,  1.        ],
        [ 2.        ,  3.        ],
        [ 4.        ,  5.        ]],

       [[-0.91075929, -0.14314335],
        [-0.37255076, -0.50784828],
        [-0.01510349, -0.09954732]]])

In [27]:
np.vstack([arr1,arr2])

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.91075929, -0.14314335],
       [-0.37255076, -0.50784828],
       [-0.01510349, -0.09954732]])

In [28]:
np.hstack([arr1,arr2])

array([[ 0.        ,  1.        , -0.91075929, -0.14314335],
       [ 2.        ,  3.        , -0.37255076, -0.50784828],
       [ 4.        ,  5.        , -0.01510349, -0.09954732]])

# Spliting

In [36]:
np.split(arr,3)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [37]:
#when we do vertical split it'll break in horizontal way and vice versa for horizontal split

In [46]:
np.split(arr,3)

[array([0, 1]), array([2, 3]), array([4, 5])]