In [5]:
a = [1,2,3,4,5,6,7,8,9,10]

b = []

for num in a:
        b.append(num*5)
b

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [14]:
import numpy as np
numpyarray = np.array([22,44.98,55,66], dtype = np.int8)
print(numpyarray)
print(type(numpyarray))


[22 44 55 66]
<class 'numpy.ndarray'>


In [19]:
randomArray = np.random.randn(10)*100
randomArray

array([-106.9528102 ,  165.48723023,   68.08179131,  -62.49180741,
         24.12392854,   14.38219477,  -34.66793931,  250.98245225,
         19.08676628,  -72.28497031])

In [20]:
randomArray.ndim

1

In [21]:
randomArray.shape

(10,)

In [22]:
twoD = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
twoD

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [23]:
twoD.shape

(4, 3)

In [27]:
miscD = np.array([[[[99]]]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[[99]]]]
4
(1, 1, 1, 1)


In [31]:
a = np.arange(12).reshape(4,3)

In [32]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
flat = np.ravel(a)
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
threeD = np.arange(36).reshape(6,6)

In [38]:
threeD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [39]:
twoD = threeD.reshape(3,3,4)
twoD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [40]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [9]:
import numpy as np
fourD = np.array([[[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13],[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]]])
fourD

array([[[[ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 10],
         [10, 11, 12, 13],
         [ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 10],
         [10, 11, 12, 13]]]])

In [45]:
m1 = np.arange(12).reshape(4,3)

In [15]:
import numpy as np
m2 = np.random.rand(12).reshape(4,4)
m1 + m2

ValueError: cannot reshape array of size 12 into shape (4,4)

In [48]:
m3 = np.arange(18).reshape(3,6)
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [49]:
m1


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
m1@m3

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [52]:
np.dot(m1,m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [ ]:
#they all have same function.


In [53]:
m1.dot(m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [56]:
zeroooos = np.zeros((4,5), dtype = "int8")
zeroooos

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [57]:
onessss = np.ones((5,5), dtype = "int8")
onessss

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [58]:
oness = np.ones(5,5)
oness

TypeError: data type not understood

In [61]:
fulllll = np.full((4,4),100)
fulllll

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [62]:
emptyy = np.empty((4,4,4))
emptyy

array([[[1.966e-321, 0.000e+000, 1.349e-321, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000]],

       [[0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000]],

       [[0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000]],

       [[0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000]]])

In [63]:
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [65]:
like = np.zeros_like(m3)
like

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [66]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
i = np.eye(3,3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
j = i.astype('int')
j

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [70]:
alist = [99,77,88,44]
type(alist[0:3])

list

In [72]:
tdarray = np.arange(36).reshape(6,6)
tdarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [73]:
tdarray[3,2]

20

In [74]:
tdarray[3][2]

20

In [ ]:
#Slicing

In [75]:
#tdarray[row,col]
#tdarray[start:end,start:end]
tdarray[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [76]:
tdarray[1:2,2:5]

array([[ 8,  9, 10]])

# Home Practice
import numpy as np
vv= np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
vv
vv.shape


In [21]:
flat = np.ravel(vv)
flat

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

# REVISION OF CLASS 1
#SLICING


In [ ]:
import numpy as np

In [2]:
ar = np.array([44,55,66,77])
ar

array([44, 55, 66, 77])

In [4]:
ar[2]

66

In [5]:
ar[1:2]

array([55])

In [6]:
ar2d = np.array([[22,33,44],[55,66,77],[88,99,100]])
ar2d

array([[ 22,  33,  44],
       [ 55,  66,  77],
       [ 88,  99, 100]])

In [7]:
ar2d[2]

array([ 88,  99, 100])

In [8]:
ar2d[1][2]

77

In [9]:
ar2d[1,2]

77

In [11]:
ar2d[0:2]

array([[22, 33, 44],
       [55, 66, 77]])

In [17]:
ar2d[:2,2:]

array([[44],
       [77]])

In [34]:
ar3d = np.array ([[[100,200,300],[400,500,600],[700,800,900]]])
ar3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [35]:
ar3d.ndim

3

In [36]:
ar3d.shape

(1, 3, 3)

# indexing

In [29]:
ar3d[0][2]

array([700, 800, 900])

In [44]:
ar3d[0,:2,2:]

array([[300],
       [600]])