In [1]:
import numpy as np

# Broadcasting

In [2]:
x = np.array([[1,2,3]])   #(1,3)
y = np.array([[4],[5]])  #(2,1)

In [3]:
x, y =np.broadcast_arrays(x, y)

In [4]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
y

array([[4, 4, 4],
       [5, 5, 5]])

In [6]:
x+y

array([[5, 6, 7],
       [6, 7, 8]])

Pandas 

In [7]:
import pandas as pd

# Pandas Data Structures
Series
DataFrame

####### Series ###########

In [8]:
s1 = pd.Series([11,22,33,44,55,66,77,88,99,10])

In [9]:
s1  # pandas Series object

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
9    10
dtype: int64

In [10]:
# index (0-9 default index given bhy series object)

In [11]:
s1[9]  # ACCESSING value by index

10

In [12]:
s1[[9,2,4,5,6]]  # accessing multiple values 

9    10
2    33
4    55
5    66
6    77
dtype: int64

In [13]:
s1[5]=5555  # modifying a value in s series
s1[[2,3,4,5]]=[2222,3333,4444,55555]

In [14]:
s1

0       11
1       22
2     2222
3     3333
4     4444
5    55555
6       77
7       88
8       99
9       10
dtype: int64

In [15]:
#del s1[4]  # deleting a value in series 
del s1[2]

In [16]:
s1

0       11
1       22
3     3333
4     4444
5    55555
6       77
7       88
8       99
9       10
dtype: int64

In [17]:
s1[99]=999    # insert in a series with a new index 
s1

0        11
1        22
3      3333
4      4444
5     55555
6        77
7        88
8        99
9        10
99      999
dtype: int64

# Definig our own idexes

In [20]:
s2 = pd.Series([10,20,30,40], index=["oranges","apples","bananas","Kwi"])

In [21]:
s2

oranges    10
apples     20
bananas    30
Kwi        40
dtype: int64

In [22]:
s2.index

Index(['oranges', 'apples', 'bananas', 'Kwi'], dtype='object')

In [23]:
s2.values

array([10, 20, 30, 40], dtype=int64)

In [24]:
ourIndex=["oranges","apples","bananas","Kwi"]


s2 = pd.Series([10,20,30,40], index=ourIndex)

In [25]:
s2

oranges    10
apples     20
bananas    30
Kwi        40
dtype: int64

In [30]:
s2[s2<30]

oranges    10
apples     20
dtype: int64

In [31]:
'peech' in s2    # checking if required key is in Series or not

False

In [32]:
'oranges' in s2 # checking if required key is in Series or not

True

# Creating a series by using a dictionary

In [35]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
data = pd.Series(sdata)
data

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [40]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

data1 = pd.Series(sdata, index=states) 
data1

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [41]:
data1.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [42]:
data1.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [37]:
data1['California']=55000

In [38]:
data1

California    55000.0
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

# Data Frames

In [59]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year':  [2000, 2001, 2002, 2001, 2002, 2003],
        'pop':   [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]        }
df1  = pd.DataFrame(data)
df1

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [45]:
type(df1)

pandas.core.frame.DataFrame

In [46]:
df1.shape

(6, 3)

In [53]:
df1['pop'] # selecting single columns by column header

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [54]:
df1[['pop', "year"]] # selecting multiple columns by column headers

pop  year
0  1.5  2000
1  1.7  2001
2  3.6  2002
3  2.4  2001
4  2.9  2002
5  3.2  2003

In [60]:
del df1["pop"] # deleting a column

In [61]:
df1

state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002
5  Nevada  2003

In [66]:
df1['debt']=100
df1

state  year  debt
0    Ohio  2000   100
1    Ohio  2001   100
2    Ohio  2002   100
3  Nevada  2001   100
4  Nevada  2002   100
5  Nevada  2003   100

In [67]:
df1["debt"]=[100,200,300,100,800,500]

In [68]:
df1

state  year  debt
0    Ohio  2000   100
1    Ohio  2001   200
2    Ohio  2002   300
3  Nevada  2001   100
4  Nevada  2002   800
5  Nevada  2003   500

In [69]:
df1['debt']=range(6)

In [70]:
df1

state  year  debt
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4
5  Nevada  2003     5

In [72]:
df1['debt']=df1['state']

In [73]:
df1

state  year    debt
0    Ohio  2000    Ohio
1    Ohio  2001    Ohio
2    Ohio  2002    Ohio
3  Nevada  2001  Nevada
4  Nevada  2002  Nevada
5  Nevada  2003  Nevada

In [75]:
dic  = {
       "Ai for EO":[78,89,68,90,87,86,67,49],
       "Python1":[40,78,87,49,88,78,76,75,],
       "Python2":[59,78,87,38,10,98,81,83]
      }

df = pd.DataFrame(dic, index=["Nasir", "Asad","Ramsha", 
                              "Mansoor","Saba","Saba",
                              "Hina","Ali"])
df

Ai for EO  Python1  Python2
Nasir           78       40       59
Asad            89       78       78
Ramsha          68       87       87
Mansoor         90       49       38
Saba            87       88       10
Saba            86       78       98
Hina            67       76       81
Ali             49       75       83

In [77]:
df['Total']=df['Ai for EO'] + df['Python1'] + df['Python2']

In [78]:
df

Ai for EO  Python1  Python2  Total
Nasir           78       40       59    177
Asad            89       78       78    245
Ramsha          68       87       87    242
Mansoor         90       49       38    177
Saba            87       88       10    185
Saba            86       78       98    262
Hina            67       76       81    224
Ali             49       75       83    207

In [89]:
df['status']=["Pass" if a >= 33 and p1 >= 33 and p2 >= 33 else "Fails"
              for a,p1,p2 in zip(df['Ai for EO'],df['Python1'],df['Python2'])]
df

Ai for EO  Python1  Python2  Total status
Nasir           78       40       59    177   Pass
Asad            89       78       78    245   Pass
Ramsha          68       87       87    242   Pass
Mansoor         90       49       38    177   Pass
Saba            87       88       10    185  Fails
Saba            86       78       98    262   Pass
Hina            67       76       81    224   Pass
Ali             49       75       83    207   Pass

In [81]:
numbers= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
evenArr = []
oddArr = []
for num in numbers:
    if num%2==0:
        evenArr.append(num)
    else:
        oddArr.append(num)
print("Evens>>", evenArr)
print("Odds>>>", oddArr)

Evens>> [2, 4, 6, 8, 10, 12, 14]
Odds>>> [1, 3, 5, 7, 9, 11, 13, 15]


In [88]:
[num for num in numbers ]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [90]:
a = list(range(5))
b = list(range(6,11))
a

[0, 1, 2, 3, 4]

In [93]:
b

[6, 7, 8, 9, 10]

In [92]:
c = zip(a,b)
for i in c:
    print(i)

(0, 6)
(1, 7)
(2, 8)
(3, 9)
(4, 10)


In [96]:
df['Ai for EO']

Nasir      78
Asad       89
Ramsha     68
Mansoor    90
Saba       87
Saba       86
Hina       67
Ali        49
Name: Ai for EO, dtype: int64

In [101]:
df.head()

Ai for EO  Python1  Python2  Total status
Nasir           78       40       59    177   Pass
Asad            89       78       78    245   Pass
Ramsha          68       87       87    242   Pass
Mansoor         90       49       38    177   Pass
Saba            87       88       10    185  Fails

In [102]:
df.tail()

Ai for EO  Python1  Python2  Total status
Mansoor         90       49       38    177   Pass
Saba            87       88       10    185  Fails
Saba            86       78       98    262   Pass
Hina            67       76       81    224   Pass
Ali             49       75       83    207   Pass

In [1]:
df.loc['Nasir':'Hina']

NameError: name 'df' is not defined

In [118]:
df.iloc[0:6]

Ai for EO  Python1  Python2  Total status
Nasir           78       40       59    177   Pass
Asad            89       78       78    245   Pass
Ramsha          68       87       87    242   Pass
Mansoor         90       49       38    177   Pass
Saba            87       88       10    185  Fails
Saba            86       78       98    262   Pass

In [120]:
df.loc['Hina'::-1]

Ai for EO  Python1  Python2  Total status
Hina            67       76       81    224   Pass
Saba            86       78       98    262   Pass
Saba            87       88       10    185  Fails
Mansoor         90       49       38    177   Pass
Ramsha          68       87       87    242   Pass
Asad            89       78       78    245   Pass
Nasir           78       40       59    177   Pass

In [121]:
df.iloc[::-1]

Ai for EO  Python1  Python2  Total status
Ali             49       75       83    207   Pass
Hina            67       76       81    224   Pass
Saba            86       78       98    262   Pass
Saba            87       88       10    185  Fails
Mansoor         90       49       38    177   Pass
Ramsha          68       87       87    242   Pass
Asad            89       78       78    245   Pass
Nasir           78       40       59    177   Pass

In [131]:
df.loc['abc'] = [1,2,3,4,5]

In [132]:
df

Ai for EO Python1 Python2 Total status
Nasir          78      40      59   177   Pass
Asad           89      78      78   245   Pass
Ramsha         68      87      87   242   Pass
Mansoor        90      49      38   177   Pass
Saba           87      88      10   185  Fails
Saba           86      78      98   262   Pass
Hina           67      76      81   224   Pass
Ali            49      75      83   207   Pass
abc             1       2       3     4      5

# 13.oct.2019

In [15]:
import pandas as pd

In [16]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [18]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [19]:
frame = pd.DataFrame(data, columns=['year', 'state', 'pop', 'extra'])
frame

year   state  pop extra
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [20]:
frame.columns

Index(['year', 'state', 'pop', 'extra'], dtype='object')

In [23]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [24]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
        index=['one', 'two', 'three', 'four',
        'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [25]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [26]:
pop = {'Nevada': {2001:2.4, 2002:2.9},
       'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)

In [27]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [28]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [34]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [38]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [39]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [43]:
frame3.index.name ='year';frame3.columns.name ='state'

In [44]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [45]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

# Essential Functionality

In [ ]:
Reindexing on series

In [46]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [47]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [50]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [51]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [52]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [53]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [55]:
obj3.reindex(range(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [56]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [59]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

Reindexing on frame

In [68]:
import numpy as np

In [69]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [70]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [71]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [72]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [73]:
states = ['Texas', 'Utah', 'California']

In [76]:
frame2.reindex(columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [86]:
frame2.reindex(index=['f','b','a','d','c','g'],columns=['Texas','NewYork','Utah','California','Bay'])

Texas  NewYork  Utah  California  Bay
f    NaN      NaN   NaN         NaN  NaN
b    NaN      NaN   NaN         NaN  NaN
a    1.0      NaN   NaN         2.0  NaN
d    7.0      NaN   NaN         8.0  NaN
c    4.0      NaN   NaN         5.0  NaN
g    NaN      NaN   NaN         NaN  NaN

In [87]:
frame2 = frame.reindex(['a', 'b', 'c', 'd','f','g'])

In [88]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
f   NaN    NaN         NaN
g   NaN    NaN         NaN

In [110]:
import numpy as np

In [115]:
data = pd.DataFrame(np.arange(1,101),reshape((20,5)),
                    column = ['a','b','c','d','e'],
                    index = range(1,181,5))
data

NameError: name 'reshape' is not defined

In [112]:
list('abcde')

['a', 'b', 'c', 'd', 'e']

In [116]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
f   NaN    NaN         NaN
g   NaN    NaN         NaN

In [119]:
frame2.loc['c'][2]

5.0

In [125]:
frame2.loc[::-1,::-1]

California  Texas  Ohio
g         NaN    NaN   NaN
f         NaN    NaN   NaN
d         8.0    7.0   6.0
c         5.0    4.0   3.0
b         NaN    NaN   NaN
a         2.0    1.0   0.0

In [126]:
frame2.iloc[::-1,::-1]

California  Texas  Ohio
g         NaN    NaN   NaN
f         NaN    NaN   NaN
d         8.0    7.0   6.0
c         5.0    4.0   3.0
b         NaN    NaN   NaN
a         2.0    1.0   0.0

In [130]:
frame2


Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
f   NaN    NaN         NaN
g   NaN    NaN         NaN

In [131]:
frame2.iloc[0:3]

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0

In [134]:
frame2.loc['b'][1]=2
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    2.0         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
f   NaN    NaN         NaN
g   NaN    NaN         NaN

In [139]:
frame2.loc['b']
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    2.0         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
f   NaN    NaN         NaN
g   NaN    NaN         NaN

In [148]:
frame2.loc['b'][[2,0]] = frame2.loc['b'][[0,2]]

In [149]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    2.0         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
f   NaN    NaN         NaN
g   NaN    NaN         NaN

In [162]:
#frame2['Texas'][4] + [5]
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    2.0         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
f   NaN    NaN         NaN
g   NaN    NaN         NaN

In [160]:
frame4 = frame2.copy()
frame4

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    2.0         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
f   NaN    NaN         NaN
g   NaN    NaN         NaN

In [163]:
frame4['std'] = [4,5,7,8,9,0]
frame4

Ohio  Texas  California  std
a   0.0    1.0         2.0    4
b   NaN    2.0         NaN    5
c   3.0    4.0         5.0    7
d   6.0    7.0         8.0    8
f   NaN    NaN         NaN    9
g   NaN    NaN         NaN    0

In [179]:
frame4.loc[::-1,'California'::-1]

California  Texas  Ohio
g         NaN    NaN   NaN
f         NaN    NaN   NaN
d         8.0    7.0   6.0
c         5.0    4.0   3.0
b         NaN    2.0   NaN
a         2.0    1.0   0.0

In [180]:
frame4.iloc[0:3]

Ohio  Texas  California  std
a   0.0    1.0         2.0    4
b   NaN    2.0         NaN    5
c   3.0    4.0         5.0    7

In [181]:
frame4[frame4 > 5]

Ohio  Texas  California  std
a   NaN    NaN         NaN  NaN
b   NaN    NaN         NaN  NaN
c   NaN    NaN         NaN  7.0
d   6.0    7.0         8.0  8.0
f   NaN    NaN         NaN  9.0
g   NaN    NaN         NaN  NaN

In [182]:
frame4.fillna(0,inplace=True)

In [183]:
frame4

Ohio  Texas  California  std
a   0.0    1.0         2.0    4
b   0.0    2.0         0.0    5
c   3.0    4.0         5.0    7
d   6.0    7.0         8.0    8
f   0.0    0.0         0.0    9
g   0.0    0.0         0.0    0

In [191]:
df = pd.read_csv ('data.csv')
df.head()

Student Code  Degree     Student Name  Mid  Quiz 1  Quiz 2  \
0   022-14-19987  BS(CS)      Abdul Basit   28     8.0     3.0   
1  022-14-110233  BS(CS)      Adeel Ahmed   17     NaN     5.0   
2  022-14-110585  BS(CS)     Afrah Zareen   18     5.0     2.0   
3   022-14-19718  BS(CS)   Ahmed Ali Raza   14     7.0     2.0   
4  022-14-110648  BS(CS)  Ahsan Ali Vohra   27     7.0     6.0   

   Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0                8           7.0           9.0                    9   
1                5           8.0          10.0                   10   
2                5           8.0          10.0                   10   
3                7           NaN           2.0                    2   
4                7           7.0           9.0                    9   

   Total Sessional (50)  Final (50)  Total (100) Grade  
0                    45        25.0           70     B  
1                    32        18.0           50     F  
2                    33        30.0           63     C  
3                    23        23.0           46     F  
4                    43        34.0           77     B

In [224]:
df[df['Best of Quizzes' and 'Best of Assignments'] > 7].count()

Student Code            41
Degree                  41
Student Name            41
Mid                     41
Quiz 1                  39
Quiz 2                  39
Best of Quizzes         41
Assignment 1            40
Assignment 2            33
Best of Assignments     41
Total Sessional (50)    41
Final (50)              41
Total (100)             41
Grade                   41
dtype: int64